[input]
files = [
  {path = ".ci/output/guide/neuron.html", url=".ci/output/guide/neuron.html", title = """Migrating from neuron – Emanote"""},
  {path = ".ci/output/guide/uptree.html", url=".ci/output/guide/uptree.html", title = """Uplink tree – Emanote"""},
  {path = ".ci/output/index.html", url=".ci/output/index.html", title = """Emanote"""},
  {path = ".ci/output/demo.html", url=".ci/output/demo.html", title = """Demo – Emanote Demos"""},
  {path = ".ci/output/resources.html", url=".ci/output/resources.html", title = """Resources – Emanote"""},
  {path = ".ci/output/architecture.html", url=".ci/output/architecture.html", title = """Architecture – Emanote"""},
  {path = ".ci/output/examples.html", url=".ci/output/examples.html", title = """Examples – Emanote"""},
  {path = ".ci/output/guide.html", url=".ci/output/guide.html", title = """Guide – Emanote"""},
  {path = ".ci/output/resources/emanote-template.html", url=".ci/output/resources/emanote-template.html", title = """emanote-template – Emanote"""},
  {path = ".ci/output/resources/vim.html", url=".ci/output/resources/vim.html", title = """Vim – Emanote"""},
  {path = ".ci/output/resources/zk.html", url=".ci/output/resources/zk.html", title = """zk – Emanote"""},
  {path = ".ci/output/resources/vscode.html", url=".ci/output/resources/vscode.html", title = """Visual Studio Code – Emanote"""},
  {path = ".ci/output/tips.html", url=".ci/output/tips.html", title = """Tips – Emanote"""},
  {path = ".ci/output/tips/wsl.html", url=".ci/output/tips/wsl.html", title = """Using on Windows – Emanote"""},
  {path = ".ci/output/tips/nix.html", url=".ci/output/tips/nix.html", title = """Using on Nix/NixOS – Emanote"""},
  {path = ".ci/output/tips/adding-images.html", url=".ci/output/tips/adding-images.html", title = """Adding Images – Emanote"""},
  {path = ".ci/output/tips/js.html", url=".ci/output/tips/js.html", title = """JavaScript behaviours – Emanote"""},
  {path = ".ci/output/tips/js/syntax-highlighting.html", url=".ci/output/tips/js/syntax-highlighting.html", title = """Syntax Highlighting – Emanote"""},
  {path = ".ci/output/tips/js/mermaid.html", url=".ci/output/tips/js/mermaid.html", title = """Mermaid Diagrams – Emanote"""},
  {path = ".ci/output/tips/js/math.html", url=".ci/output/tips/js/math.html", title = """Math – Emanote"""},
  {path = ".ci/output/tips/sync.html", url=".ci/output/tips/sync.html", title = """Synchronizing notes using Syncthing – Emanote"""},
  {path = ".ci/output/start/install/docker.html", url=".ci/output/start/install/docker.html", title = """Docker image – Emanote"""},
  {path = ".ci/output/start/install.html", url=".ci/output/start/install.html", title = """Installing – Emanote"""},
  {path = ".ci/output/demo/yaml-config.html", url=".ci/output/demo/yaml-config.html", title = """YAML configuration – Emanote Demos"""},
  {path = ".ci/output/demo/orgmode.html", url=".ci/output/demo/orgmode.html", title = """Org Mode – Emanote Demos"""},
  {path = ".ci/output/demo/neuron-layout.html", url=".ci/output/demo/neuron-layout.html", title = """Neuron-like layout – Emanote Demos"""},
  {path = ".ci/output/demo/embed.html", url=".ci/output/demo/embed.html", title = """Embedding – Emanote Demos"""},
  {path = ".ci/output/demo/markdown.html", url=".ci/output/demo/markdown.html", title = """Extended Markdown ✍️ – Emanote Demos"""},
  {path = ".ci/output/demo/custom-style.html", url=".ci/output/demo/custom-style.html", title = """Custom CSS styling – Emanote Demos"""},
  {path = ".ci/output/demo/lua-filters.html", url=".ci/output/demo/lua-filters.html", title = """Pandoc Lua Filters – Emanote Demos"""},
  {path = ".ci/output/demo/file-links.html", url=".ci/output/demo/file-links.html", title = """File WikiLinks – Emanote Demos"""},
  {path = ".ci/output/start.html", url=".ci/output/start.html", title = """Getting Started – Emanote"""},
]
