[input]
files = [
  {path = "guide/neuron.html", url="guide/neuron.html", title = """Migrating from neuron – Emanote"""},
  {path = "guide/uptree.html", url="guide/uptree.html", title = """Uplink tree – Emanote"""},
  {path = "index.html", url="index.html", title = """Emanote"""},
  {path = "demo.html", url="demo.html", title = """Demo – Emanote Demos"""},
  {path = "resources.html", url="resources.html", title = """Resources – Emanote"""},
  {path = "architecture.html", url="architecture.html", title = """Architecture – Emanote"""},
  {path = "examples.html", url="examples.html", title = """Examples – Emanote"""},
  {path = "guide.html", url="guide.html", title = """Guide – Emanote"""},
  {path = "resources/emanote-template.html", url="resources/emanote-template.html", title = """emanote-template – Emanote"""},
  {path = "resources/vim.html", url="resources/vim.html", title = """Vim – Emanote"""},
  {path = "resources/zk.html", url="resources/zk.html", title = """zk – Emanote"""},
  {path = "resources/vscode.html", url="resources/vscode.html", title = """Visual Studio Code – Emanote"""},
  {path = "tips.html", url="tips.html", title = """Tips – Emanote"""},
  {path = "tips/wsl.html", url="tips/wsl.html", title = """Using on Windows – Emanote"""},
  {path = "tips/nix.html", url="tips/nix.html", title = """Using on Nix/NixOS – Emanote"""},
  {path = "tips/adding-images.html", url="tips/adding-images.html", title = """Adding Images – Emanote"""},
  {path = "tips/js.html", url="tips/js.html", title = """JavaScript behaviours – Emanote"""},
  {path = "tips/js/syntax-highlighting.html", url="tips/js/syntax-highlighting.html", title = """Syntax Highlighting – Emanote"""},
  {path = "tips/js/mermaid.html", url="tips/js/mermaid.html", title = """Mermaid Diagrams – Emanote"""},
  {path = "tips/js/math.html", url="tips/js/math.html", title = """Math – Emanote"""},
  {path = "tips/sync.html", url="tips/sync.html", title = """Synchronizing notes using Syncthing – Emanote"""},
  {path = "start/install/docker.html", url="start/install/docker.html", title = """Docker image – Emanote"""},
  {path = "start/install.html", url="start/install.html", title = """Installing – Emanote"""},
  {path = "demo/yaml-config.html", url="demo/yaml-config.html", title = """YAML configuration – Emanote Demos"""},
  {path = "demo/orgmode.html", url="demo/orgmode.html", title = """Org Mode – Emanote Demos"""},
  {path = "demo/neuron-layout.html", url="demo/neuron-layout.html", title = """Neuron-like layout – Emanote Demos"""},
  {path = "demo/embed.html", url="demo/embed.html", title = """Embedding – Emanote Demos"""},
  {path = "demo/markdown.html", url="demo/markdown.html", title = """Extended Markdown ✍️ – Emanote Demos"""},
  {path = "demo/custom-style.html", url="demo/custom-style.html", title = """Custom CSS styling – Emanote Demos"""},
  {path = "demo/lua-filters.html", url="demo/lua-filters.html", title = """Pandoc Lua Filters – Emanote Demos"""},
  {path = "demo/file-links.html", url="demo/file-links.html", title = """File WikiLinks – Emanote Demos"""},
  {path = "start.html", url="start.html", title = """Getting Started – Emanote"""},
]
